service: simple-aws-lambda

provider:
  name: aws
  runtime: java17
  region: us-east-1
  timeout: 10
  memorySize: 1024
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
        - !Join [ '', [ 'arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*' ] ]
custom:
  myBucket: hamza-custom-bucket
package:
  artifact: target/simple-aws-lambda.jar

functions:
  simpleLambda:
    handler: ma.DS.SimpleLambda
    environment:
      MESSAGE: Hamza brs

  simpleHttp:
    handler: ma.DS.SimpleHttpHandler
    events:
      - httpApi:
          path: /simple
          method: POST  # Use uppercase POST

  simpleEventTrigger:
    handler: ma.DS.SimpleEventHandler
    events:
      - s3:
          bucket: ${self:custom.myBucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png
